### ISSUE TITLE
how mount host dir regarding not matching uid's problems?

### ISSUE THREAD

**Issue by shuron** [binhex/arch-minidlna#1]
do you have some best practice for handling failure of host mounts in case of different ui's...
Because container runs root (uid=0) and dlna meadia is often in user space with (uid=1000>)
So it's tricky to use your image out of the box...  Any ideas?

**Comment by aholbreich** [comment]
Commentless closing?
Looks like these two flags are meant to be the solution for the problem i've mentioned:
"-e PUID=0  -e PGID=0 "

**Comment by binhex** [comment]
sorry i wasn't monitoring github for issues and as this issue is VERY old i assumed the person who posted the issue probably either doesn't care about it any more or has seen that ive now included support for user id and group id thus the close :-).

just to confirm, yes your correct, this is now supported via the PUID and PGID env vars, if any issues then please feel free to re-open the issue.

**Comment by aholbreich** [comment]
Thank you clarifying this.:) Just realizing that i've not updated my minidlna so long...
